spring:
  application:
    name: provider
  redis:
    host: localhost
    port: 6379
    database: 5
    timeout: 36000
server:
  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
env:
  dev
